executor:
  url: https://books.toscrape.com/
  headers:
    accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
    accept-language: 'en-US,en;q=0.9'
    user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36'
    referer: 'https://www.google.com/' 
    sec-ch-ua: '"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"' 

transformation:
  rating_map:
    One: 1
    Two: 2
    Three: 3
    Four: 4
    Five: 5